<%@ Page Language="C#" MasterPageFile="~/Default.master" AutoEventWireup="true" CodeFile="CargosPessoa.aspx.cs"
    Inherits="_CargosPessoa" ValidateRequest="false" Title="CargosPessoa" %>

<asp:Content ID="Content2" ContentPlaceHolderID="head" runat="Server">
</asp:Content>
<asp:Content ID="Content1" ContentPlaceHolderID="ContentPlaceHolder1" runat="Server">
    <h1>
        Cargos Pessoa</h1>
        
    <asp:Button ID="btnAdicionarPrimeiroNivel" runat="server" Text="Adicionar Primeiro Nivel" OnClick="btnAdicionarPrimeiroNivel_Click" />
        
    <asp:TextBox ID="txtIdPessoa" runat="server" Visible="false"></asp:TextBox>
    <div id="dvCargos" runat="server">
        <div style="min-width: 500px; float: left">
            <fieldset style="min-height: 500px">
                <legend>Adicionar pessoas </legend>
                <asp:TreeView ID="trvPessoas" runat="server" AutoGenerateDataBindings="False"
                    ShowLines="True" OnSelectedNodeChanged="trvPessoas_SelectedNodeChanged">
                </asp:TreeView>
            </fieldset>
        </div>
        <div style="min-width: 300px; float: left">
            <fieldset style="min-height: 500px">
                <legend id="legendAddPessoas" runat="server">Adicionar em  </legend>                
                <br />
                <asp:Button ID="btnAddPessoas" Width="200px" runat="server" Text="Adicionar pessoas fisicas" OnClick="btnAddPessoas_Click" />
            </fieldset>
        </div>
        </fieldset>
    </div>
    <div id="dvAdicionarPessoas" visible="false" runat="server">
        <fieldset style="min-height: 500px">
            <legend id="legendPessoasFisica" runat="server">Pessoas Fisicas</legend>
            <table style="width: 100% border: 0px" id="tableAddPessoas" runat="server">
                <tr>
                    <td style="width: 100px">
                        <div>
                            Razão social:
                            <asp:TextBox ID="txtData" Width="202px" runat="server"></asp:TextBox><asp:Button
                                ID="btnFind" runat="server" Text="Ok" OnClick="btnFind_Click" />
                        </div>
                        <asp:ListBox ID="listPessoasFisicas" runat="server" Height="330px" Width="300px"
                            SelectionMode="Multiple"></asp:ListBox>
                    </td>
                    <td align="center">
                        <asp:Button ID="btnDelete" CssClass="btn" runat="server" Text="<<" OnClick="btnDelete_Click" />
                        <asp:Button ID="btnAdd" CssClass="btn" runat="server" Text=">>" OnClick="btnAdd_Click" />
                    </td>
                    <td style="width: 100px">
                        <asp:ListBox ID="listPessoasFisicasAdd" runat="server" Height="330px" Width="300px"
                            SelectionMode="Multiple"></asp:ListBox>
                    </td>
                </tr>
            </table>
            <asp:Button ID="btnVoltarFisica" runat="server" Text="Voltar" OnClick="btnVoltarFisica_Click" />
        </fieldset>
    </div>  
</asp:Content>
